name: WinRAR Keygen Secrets

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Generate key 
      shell: powershell
      run: bin/x64-Release/winrar-keygen.exe "${{secrets.TEXT1}}" "${{secrets.TEXT2}}" | out-file -encoding ascii rarreg.key
      
    - name: Upload key
      uses: actions/upload-artifact@v2.3.1
      with:
        name: rarreg_file
        path: rarreg.key
        retention-days: 90